name: ci-flutter-workflow
on:
  - pull_request:
      branches:
        - development

jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: dart test
